### ISSUE TITLE
Error - loading mod

### ISSUE THREAD

**Issue by RstYcz** [MrCrayfish/MrCrayfishMoreFurnitureMod#6]
-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.morefurniture.init.ModBlocks.<clinit>(ModBlocks.java:28) ~[?:task ':jar' property 'archiveVersion'] {re:classloading}
-- MOD morecfm --
Details:
	Mod File: morecfm-1.3.0-1.16.3.jar
	Failure message: MrCrayfish's More Furniture Mod (morecfm) has failed to load correctly
		java.lang.NoSuchFieldError: WOOD
	Mod Version: 1.3.0
	Mod Issue URL: https://github.com/MrCrayfish/MrCrayfishMoreFurnitureMod/issues
	Exception message: java.lang.NoSuchFieldError: WOOD
Stacktrace:
	at com.mrcrayfish.morefurniture.init.ModBlocks.<clinit>(ModBlocks.java:28) ~[?:task ':jar' property 'archiveVersion'] {re:classloading}
	at com.mrcrayfish.morefurniture.MoreFurnitureMod.<init>(MoreFurnitureMod.java:49) ~[?:task ':jar' property 'archiveVersion'] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3128/1799545709.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3234/925455585.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

![image](https://user-images.githubusercontent.com/66439540/121556774-75d54580-ca14-11eb-94d5-297728024e76.png)

**Comment by MrCrayfish** [comment]
Download 1.3.1
